var word = 'JavaScript'; 
var second = 'is'; 
var third = 'awesome'; 
var fourth = 'and'; 
var fifth = 'I'; 
var sixth = 'love'; 
var seventh = 'it!';
console.log(word+second+third+fourth+fifth+sixth+seventh);
// console.log(word);
// console.log(second);
// console.log(third);
// console.log(fourth);
// console.log(fifth);
// console.log(sixth);
// console.log(seventh);
